version: '3'
services:
  murkel2:
    image: ghcr.io/relativity74205/murkelhausen_app_v2/murkel_app2:0.4.0
    container_name: murkelhausen2
    restart: always
    ports:
      - "3333:3000"
      - "8333:8333"
    hostname: murkel2
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
#      - DJANGO__SECRET_KEY=${DJANGO__SECRET_KEY}
#      - DJANGO__DEBUG=${DJANGO__DEBUG}
#      - DJANGO__ALLOWED_HOSTS=${DJANGO__ALLOWED_HOSTS}
#      - OPENAI_API_KEY=${OPENAI_API_KEY}
#      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}