version: '3'
services:
  murkel2:
    image: ghcr.io/relativity74205/murkelhausen_app_v2/murkel_app2:0.7.1
    container_name: murkelhausen2
    restart: always
    ports:
      - "3333:3000"
      - "8333:8333"
    hostname: murkel2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - PI_HOLE_TOKEN=${PI_HOLE_TOKEN}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      - PODCASTINDEX_API_SECRET=${PODCASTINDEX_API_SECRET}
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}