version: '3'
services:
  murkel2:
    image: ghcr.io/relativity74205/murkelhausen_app_v2/murkel_app2:0.11.0
    container_name: murkelhausen2
    restart: always
    ports:
      - "3333:3000"
      - "8333:8333"
    hostname: murkel2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - PI_HOLE_TOKEN=${PI_HOLE_TOKEN}
      - PODCASTINDEX_API_SECRET=${PODCASTINDEX_API_SECRET}
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      - GOOGLE_CLIENT_EMAIL=${GOOGLE_CLIENT_EMAIL}
      - GOOGLE_CALENDAR_ARKADIUS=${GOOGLE_CALENDAR_ARKADIUS}
      - GOOGLE_CALENDAR_FAMILIE=${GOOGLE_CALENDAR_FAMILIE}
      - GOOGLE_CALENDAR_ERIK=${GOOGLE_CALENDAR_ERIK}
      - GOOGLE_CALENDAR_MATTIS=${GOOGLE_CALENDAR_MATTIS}
      - GOOGLE_CALENDAR_ANDREA=${GOOGLE_CALENDAR_ANDREA}
      - GOOGLE_CALENDAR_GEBURTSTAGE=${GOOGLE_CALENDAR_GEBURTSTAGE}
      - PUSHOVER_USER_KEY=${PUSHOVER_USER_KEY}
      - PUSHOVER_TOKEN=${PUSHOVER_TOKEN}