"""empty message

Revision ID: 3b6acd6a5397
Revises: 99bbaa0045ee
Create Date: 2025-02-09 21:13:42.134716

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b6acd6a5397"
down_revision: Union[str, None] = "99bbaa0045ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "time_table_erik",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("block", sa.Integer(), nullable=False),
        sa.Column("timeframe", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject_monday", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("subject_tuesday", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "subject_wednesday", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "subject_thursday", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("subject_friday", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("time_table_erik")
    # ### end Alembic commands ###
