"""empty message

Revision ID: 691ecbcab429
Revises: 3b6acd6a5397
Create Date: 2025-02-18 21:09:06.769810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '691ecbcab429'
down_revision: Union[str, None] = '3b6acd6a5397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_table_andrea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block', sa.Integer(), nullable=False),
    sa.Column('timeframe', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_monday', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subject_tuesday', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subject_wednesday', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subject_thursday', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subject_friday', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_table_andrea')
    # ### end Alembic commands ###
