"""empty message

Revision ID: 77ac4dbbe84b
Revises: 511852c42a0c
Create Date: 2025-02-09 20:50:57.523521

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77ac4dbbe84b"
down_revision: Union[str, None] = "511852c42a0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timetablemattis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("block", sa.Integer(), nullable=False),
        sa.Column("timeframe", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject_monday", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "subject_tuesday", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "subject_wednesday", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "subject_thursday", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("subject_friday", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("timetablemattis")
    # ### end Alembic commands ###
