"""empty message

Revision ID: 81be14b6398a
Revises: e431e8f02176
Create Date: 2025-02-09 20:55:26.201811

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81be14b6398a"
down_revision: Union[str, None] = "e431e8f02176"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("time_table_mattis", schema=None) as batch_op:
        batch_op.alter_column(
            "subject_monday", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "subject_tuesday", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "subject_wednesday", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "subject_thursday", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "subject_friday", existing_type=sa.VARCHAR(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("time_table_mattis", schema=None) as batch_op:
        batch_op.alter_column(
            "subject_friday", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "subject_thursday", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "subject_wednesday", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "subject_tuesday", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "subject_monday", existing_type=sa.VARCHAR(), nullable=False
        )

    # ### end Alembic commands ###
