"""empty message

Revision ID: 99bbaa0045ee
Revises: 81be14b6398a
Create Date: 2025-02-09 20:56:15.184357

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99bbaa0045ee"
down_revision: Union[str, None] = "81be14b6398a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("time_table_mattis", schema=None) as batch_op:
        batch_op.add_column(sa.Column("even_week", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("time_table_mattis", schema=None) as batch_op:
        batch_op.drop_column("even_week")

    # ### end Alembic commands ###
