"""empty message

Revision ID: e431e8f02176
Revises: 77ac4dbbe84b
Create Date: 2025-02-09 20:52:17.573753

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e431e8f02176"
down_revision: Union[str, None] = "77ac4dbbe84b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "time_table_mattis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("block", sa.Integer(), nullable=False),
        sa.Column("timeframe", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject_monday", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "subject_tuesday", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "subject_wednesday", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "subject_thursday", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("subject_friday", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("timetablemattis")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timetablemattis",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("block", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("subject_monday", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("subject_tuesday", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "subject_wednesday", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "subject_thursday", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("subject_friday", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="timetablemattis_pkey"),
    )
    op.drop_table("time_table_mattis")
    # ### end Alembic commands ###
